# Generated by Django 4.1 on 2022-10-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
