# Generated by Django 4.1 on 2022-10-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publicaciones_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='fecha',
        ),
    ]
