# Generated by Django 4.1 on 2022-09-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='especie',
            field=models.IntegerField(choices=[[0, 'Perro'], [1, 'Gato'], [2, 'Otro']], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='raza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
