# Generated by Django 4.1 on 2022-10-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_publicaciones_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
