# Generated by Django 4.1 on 2022-10-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_publicaciones_especie_publicaciones_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='especie',
            field=models.IntegerField(choices=[['Perro', 'Perro'], ['Gato', 'Gato'], ['Otro', 'Otro']]),
        ),
    ]
