# Generated by Django 4.1 on 2022-10-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_publicaciones_especie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='especie',
        ),
    ]
