# Generated by Django 4.1 on 2022-10-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_publicaciones_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='user',
        ),
    ]
