# Generated by Django 4.1 on 2022-10-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_publicaciones_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='especie',
            field=models.IntegerField(choices=[(0, 'Sin Definir'), (1, 'Perro'), (2, 'Gato'), (3, 'Otro')], default=0),
            preserve_default=False,
        ),
    ]
