# Generated by Django 4.1 on 2022-10-04 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_publicaciones_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='user',
        ),
    ]
