# Generated by Django 4.1 on 2022-10-07 16:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_publicaciones_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(upload_to='imagenes'),
        ),
        migrations.CreateModel(
            name='MasInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('sexo', models.IntegerField(choices=[(0, 'Sin Definir'), (1, 'masculino'), (2, 'Femenino')])),
                ('provincia', models.IntegerField(choices=[(0, 'Buenos Aires'), (1, 'Ciudad Autónoma de Buenos Aires'), (2, 'Catamarca'), (3, 'Chaco'), (4, 'Chubut'), (5, 'Córdoba'), (6, 'Corrientes'), (7, 'Entre Ríos'), (8, 'Formosa'), (9, 'Jujuy'), (10, 'La Pampa'), (11, 'La Rioja'), (12, 'Mendoza'), (13, 'Misiones'), (14, 'Neuquén'), (15, 'Río Negro'), (16, 'Salta'), (17, 'San Juan'), (18, 'San Luis'), (19, 'Santa Cruz'), (20, 'Santa Fe'), (21, 'Santiago del Estero'), (22, 'Tierra del Fuego'), (23, 'Tucumán')])),
                ('localidad', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
