# Generated by Django 4.1.2 on 2022-10-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_gatos_remove_masinformacion_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='especie',
            field=models.IntegerField(choices=[('Sin Definir', 'Sin Definir'), ('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')]),
        ),
    ]
