# Generated by Django 4.1.2 on 2022-10-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_publicaciones_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='especie',
            field=models.IntegerField(choices=[(0, 'Sin Definir'), (1, 'Perro'), (2, 'Gato'), (3, 'Otro')]),
        ),
    ]
